# Site settings
title: Cafe del Quindio - Colombia
email: info@cafedelquindio.cf
url: https://cafegourmet.cf
description: "Cafe 100% de origen Colombiano. Ofrecemos diferentes opciones de consumo, Cafés Gourmet, Especiales de Origen y derivados de Café."
keywords: "productos de café, ESCUELA,CAFÉ , escuela de café, capacitar, calidad,Colombia, café del quindío, café quindío, cafecitas, arequipe de café, café gourmet, cafés especiales, armenia quindío colombia, galletas de café, génova, cafés de origen"
baseurl: ""

# Color settings
color:
  primary-dark: '#000000'
  links: '#FFFFFF'

# Footer settings
footer: Cafe del Quindio

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/CafeDelQuindio
  - title: facebook
    url: https://facebook.com/CafeDelQuindio
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
